name: pytest
on: workflow_dispatch 

  
jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to my workspace
        uses: actions/checkout@v3
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
      # - name: print github action context
      #   run: |
      #     echo ${{ github.repositoryUrl }}
      #     pwd
      # - name: checkout code
      #   uses: actions/checkout@v3
      # - name: install pytest
      #   run: |
      #     pip install pytest
      #     pwd
      # - name: run pytest
      #   run: |
      #     pytest
      #     pwd
